all: 1 2	 4 6 7 8 

1: 1.cc
	gcc -Wall -std=c++0x -gstabs -I. -lstdc++ -lm -o 1 1.cc 

2: 2.cc
	gcc -Wall -std=c++0x -gstabs -I. -lstdc++ -lm -o 2 2.cc 


4: 4.cc
	gcc -Wall -std=c++0x -gstabs -I. -lstdc++ -lm -o 4 4.cc

6: 6.c
	gcc -Wall -std=c99 -gstabs -I. -lstdc++ -lm -o 6 6.c 

7: 7.cc
	gcc -Wall -std=c++0x -gstabs -I. -lstdc++ -lm -o 7 7.cc 

8: 8.cc
	gcc -Wall -std=c++0x -gstabs -I. -lstdc++ -lm -o 8 8.cc


