all: 1 4 6 7 8 

1: 1.C
	gcc -Wall -std=c++0x -gstabs -I. -lstdc++ -lm -o 1 1.C 

4: 4.C
	gcc -Wall -std=c++0x -gstabs -I. -lstdc++ -lm -o 4 4.C 

6: 6.c
	gcc -Wall -std=c99 -gstabs -I. -lstdc++ -lm -o 6 6.c 

7: 7.C
	gcc -Wall -std=c++0x -gstabs -I. -lstdc++ -lm -o 7 7.C 

8: 8.C
	gcc -Wall -std=c++0x -gstabs -I. -lstdc++ -lm -o 8 8.C 

